version: '3'
services:

  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    expose:
      - 5432
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development

  dummy:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    environment:
      RAILS_ENV: "development"
      POSTGRES_DB: "development"
      # SECRET_KEY_BASE: "8bd2ce5eb177ca1a2fbe752302ac77d5cad6698de75cdecd24ccfe9a02a8d174c354f654a15bd9f04a89973990bc7ac3cdd7121861ad2615fc1296e16c042c28"
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
    command: "bundle exec rails server --binding 0.0.0.0 --port 3000"

  builder:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - gem-volume:/usr/local/bundle
    command: "bundle exec rake app:matestack_ui_bootstrap:webpacker:compile"

  redis:
    restart: always
    image: redis:5.0.7-alpine
    volumes:
      - redis-volume:/data

volumes:
  data-volume:
  gem-volume:
  node-volume:
  dummy-node-volume:
  redis-volume:
  builder-node-volume:
