FROM ruby:3.1-alpine3.16

ENV RAILS_ENV test

RUN gem install bundler:2.4.9

RUN apk update --no-cache && \
    apk add build-base postgresql-dev git nodejs yarn tzdata bash sqlite-dev shared-mime-info npm gcompat && \
    mkdir -p /app

WORKDIR /app

COPY ./lib/ /app/lib/
COPY matestack-ui-bootstrap.gemspec /app/
COPY ./ci/Gemfile.7.0 /app/Gemfile
RUN bundle install

COPY package.json /app/
RUN yarn install

RUN apk update && apk upgrade \
    && echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
    && echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories \
    && apk add --no-cache \
    chromium=102.0.5005.182-r0 \
    nss=3.78.1-r0 \
    && rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/*

RUN apk add chromium-chromedriver=102.0.5005.182-r0

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/

RUN mv Gemfile _Gemfile
RUN mv Gemfile.lock _Gemfile.lock
RUN mv yarn.lock _yarn.lock
COPY . /app
RUN rm Gemfile
RUN rm Gemfile.lock
RUN rm yarn.lock
RUN mv _Gemfile Gemfile
RUN mv _Gemfile.lock Gemfile.lock
RUN mv _yarn.lock yarn.lock

WORKDIR /app/spec/dummy

RUN npm install


RUN rm ./db/schema.rb
RUN rm ./config/application.rb
RUN mv ./config/application.7.0_rb /app/spec/dummy/config/application.rb

WORKDIR /app

RUN yarn upgrade # quick fix for vue import issues

WORKDIR /app/spec/dummy

RUN ./bin/webpack

WORKDIR /app
